#!/command/with-contenv bash
# shellcheck shell=bash

set -e

. /usr/bin/common.sh

cd /app || exit 1

log_info 'Starting backend ...'

if [ "${DEVELOPMENT:-}" = 'true' ]; then
	exec s6-setuidgid "$PUID:$PGID" bash -c "export HOME=$NPMHOME; ./npm-backend"
else
	while :
	do
		s6-setuidgid "$PUID:$PGID" bash -c "export HOME=$NPMHOME; ./npm-backend"
		sleep 1
	done
fi
