#!/command/with-contenv bash
# shellcheck shell=bash

set -e

. /usr/bin/common.sh

cd /app || exit 1

log_info 'Starting backend ...'

if [ "${DEVELOPMENT:-}" = 'true' ]; then
	# Keep container dependencies isolated from host node_modules. This is
	# especially important when the host is Windows and the container is Linux.
	mkdir -p /app/node_modules
	chown -R "$PUID:$PGID" /app/node_modules
	s6-setuidgid "$PUID:$PGID" yarn install
	exec s6-setuidgid "$PUID:$PGID" bash -c "export HOME=$NPMHOME;export CERTBOT_VERSION=$CERTBOT_VERSION;node --max_old_space_size=250 --abort_on_uncaught_exception node_modules/nodemon/bin/nodemon.js"
else
	while :
	do
		s6-setuidgid "$PUID:$PGID" bash -c "export HOME=$NPMHOME;export CERTBOT_VERSION=$CERTBOT_VERSION;node --abort_on_uncaught_exception --max_old_space_size=250 index.js"
		sleep 1
	done
fi
