#!/command/with-contenv bash
# shellcheck shell=bash

set -e

. /bin/common.sh

if [ "$(is_true "$DEBUG")" = '1' ]; then
	set -x
fi

log_info 'Starting nginx ...'
exec s6-setuidgid "$PUID:$PGID" nginx
