#!/usr/bin/with-contenv bash

# This service is DEVELOPMENT only.

if [ "$DEVELOPMENT" == "true" ]; then
	CI=true
	HOME=/tmp/npmuserhome
	export CI
	export HOME
	cd /app/frontend || exit 1
	s6-setuidgid npmuser yarn install
	s6-setuidgid npmuser yarn start
else
	exit 0
fi
