#!/command/with-contenv bash
# shellcheck shell=bash

set -e

# This service is DEVELOPMENT only.

if [ "$DEVELOPMENT" == "true" ]; then
	. /bin/common.sh
	cd /app/frontend || exit 1
	HOME=/tmp/npmuserhome
	export HOME
	mkdir -p /app/frontend/dist
	chown -R "$PUID:$PGID" /app/frontend/dist

	if [ "$PUID" = '0' ]; then
		log_info 'Starting frontend ...'
		yarn install
		exec yarn watch
	else
		log_info "Starting frontend as npmuser ($PUID) ..."
		s6-setuidgid npmuser yarn install
		exec s6-setuidgid npmuser yarn watch
	fi
else
	exit 0
fi
