#!/command/with-contenv bash
set -e

# This service is DEVELOPMENT only.

if [ "$DEVELOPMENT" == "true" ]; then
	CI=true
	HOME=/tmp/npmuserhome
	export CI
	export HOME
	cd /app/frontend || exit 1
	s6-setuidgid npmuser yarn install
	exec s6-setuidgid npmuser yarn start
else
	exit 0
fi
