#!/command/with-contenv bash
# shellcheck shell=bash

set -e

# This service is DEVELOPMENT only.

if [ "$DEVELOPMENT" == "true" ]; then
	cd /app/frontend || exit 1
	# If yarn install fails: add --verbose --network-concurrency 1
	yarn install
	yarn watch
else
	exit 0
fi
