location ~* ^.*\.(css|js|jpe?g|gif|png|webp|woff|woff2|eot|ttf|svg|ico|css\.map|js\.map)$ {
	# cache 200s and also 404s (not ideal but there are a few 404 images for some reason)
	proxy_cache_valid any 30m;
	proxy_cache_valid 404 1m;

	expires @30m;

	include conf.d/include/assets-common.conf;
}
