#!/usr/bin/with-contenv bash

mkdir -p /tmp/nginx/body \
  /var/log/nginx \
  /data/{nginx,logs,access} \
  /data/nginx/{proxy_host,redirection_host,stream,dead_host,temp} \
  /var/lib/nginx/cache/{public,private}

touch /var/log/nginx/error.log && chmod 777 /var/log/nginx/error.log
chown root /tmp/nginx

exec nginx
