#!/usr/bin/with-contenv bash

mkdir -p /tmp/nginx \
  /data/{nginx,logs,access} \
  /data/nginx/{proxy_host,redirection_host,stream,dead_host} \
  /var/lib/nginx/cache/{public,private}

chown root /tmp/nginx
exec nginx

