# WARNING: This is a CI docker-compose file used for building and testing of the entire app, it should not be used for production.
services:

  cypress:
    environment:
      CYPRESS_stack: "sqlite"
    command: cypress run --browser chrome --config-file=cypress/config/ci.mjs --expose grepTags="@isolated"

  fullstack:
    environment:
      DB_SQLITE_FILE: "/data/mydb.sqlite"
      PUID: 1000
      PGID: 1000
      DISABLE_IPV6: "true"

      # Explicitly enable HTTP/3 so that our opt-in integration tests succeed
      NPM_HTTP3_DISABLED: "0"