#!/usr/bin/with-contenv bash

mkdir -p /data/letsencrypt-acme-challenge

cd /app

while :
do
    node --abort_on_uncaught_exception --max_old_space_size=250 /app/src/backend/index.js
    sleep 1
done
