#!/command/with-contenv bash
# shellcheck shell=bash

. /bin/common.sh

if [ "$(is_true "$DEBUG")" = '1' ]; then
	set -x
fi

log_info 'Starting fail2ban ...'
exec /usr/bin/fail2ban-client -c /fail2ban -x -vv -f start
