#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/../.common.sh"

DOCKER_IMAGE=nginxproxymanager/nginx-full:certbot-node

# Ensure docker exists
if hash docker 2>/dev/null; then
	docker pull "${DOCKER_IMAGE}"
	cd "${DIR}/../.."
	echo -e "${BLUE}❯ ${CYAN}Building Frontend ...${RESET}"

	docker run --rm \
		-e CI=true \
		-e NODE_OPTIONS=--openssl-legacy-provider \
		-v "$(pwd):/app" \
		-w /app "${DOCKER_IMAGE}" \
		sh -c "set -e
			cd /app/docs && npm install && npm run build
			cd /app/frontend && yarn install && yarn lint && yarn locale-compile && yarn vitest run --no-color && yarn build
			rm -rf /app/frontend/dist/docs && mkdir -p /app/frontend/dist/docs
			cp -a /app/docs/dist/. /app/frontend/dist/docs/
			chown -R $(id -u):$(id -g) /app/frontend
		"

	echo -e "${BLUE}❯ ${GREEN}Building Frontend Complete${RESET}"
else
	echo -e "${RED}❯ docker command is not available${RESET}"
fi
