  listen 80;
{{ if .ipv6 }}
  listen [::]:80;
{{ else }}
  #listen [::]:80;
{{ end }}
{{ if .certificate }}
  listen 443 ssl;
{{ if .ipv6 }}
  listen [::]:443 ssl;
{{ else }}
  #listen [::]:443;
{{ end }}
{{ end }}
  server_name {{ join .domain_names " " }};
{{ if .http2_support }}
  http2 on;
{{ else }}
  http2 off;
{{ end }}