# ------------------------------------------------------------
# Default Site
# ------------------------------------------------------------
{{ if eq .value "congratulations" }}
# Skipping output, congratulations page configration is baked in.
{{ else }}
server {
  listen 80 default;
{{ if .ipv6 }}
  listen [::]:80 default;
{{ else }}
  #listen [::]:80 default;
{{ end }}
  server_name default-host.localhost;
  access_log /data/logs/default-host_access.log combined;
  error_log /data/logs/default-host_error.log warn;
{{ template "_exploits.conf" . }}

  include conf.d/include/letsencrypt-acme-challenge.conf;

{{ if eq .value "404" }}
  location / {
    return 404;
  }
{{ end }}

{{ if eq .value "444" }}
  location / {
    return 444;
  }
{{ end }}

{{ if eq .value "redirect" }}
  location / {
    return 301 {{ .meta.redirect }};
  }
{{ end }}

{{ if eq .value "html" }}
  root /data/nginx/default_www;
  location / {
    try_files $uri /index.html;
  }
{{ end }}
}
{{ end }}
