upstream npmplus {
  zone upstream_npmplus 64k;
  server unix:/run/npmplus.sock resolve;
}

server {
  server_name "";
  listen 0.0.0.0:81 ssl;
  listen [::]:81 ssl;
  ssl_reject_handshake on;
  return 444;
}

server {
  listen 0.0.0.0:81 ssl bind reuseport deferred multipath so_keepalive=on default_server;
  listen [::]:81 ssl bind reuseport deferred multipath so_keepalive=on default_server;

  server_name _;
  ssl_certificate ;
  ssl_certificate_key ;
  #ssl_stapling on;
  #ssl_stapling_verify on;
  #ssl_stapling_file ;
  #ssl_certificate_compression off;

  if ($scheme = "http") {
    return 301 https://$host$is_request_port$request_port$request_uri;
  }
  if ($http_x_forwarded_proto = "http") {
    return 301 https://$host$is_request_port$request_port$request_uri;
  }

  client_max_body_size 1m;
  more_set_headers "X-Frame-Options: DENY";
  more_set_headers "Referrer-Policy: no-referrer";
  more_set_headers "Content-Security-Policy: default-src 'none'; script-src-elem 'self' 'sha256-DO5PcuswBpDi7xOFPuj86dwr9VuamByHpvk2ZDmlAAA='; style-src-elem 'self' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha256-Xo8/tnRnpUxMw05nUf764oT49W2GEbQN9LaX8Wqxuwg=' 'sha256-/jDKvbQ8cdux+c5epDIqkjHbXDaIY8RucT1PmAe8FG4=' 'sha256-BeXIQk2DxxoDrgnnoH683KOnlwQvO0HH1fT4VFQTi8g=' 'sha256-RL3ie0nH+Lzz2YNqQN83mnU0J1ot4QL7b99vMdIX99w='; style-src-attr 'unsafe-hashes' 'sha256-ezdv1bOGcoOD7FKudKN0Y2Mb763O6qVtM8LT2mtanIU='; connect-src 'self' data:; img-src 'self' data:; manifest-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; upgrade-insecure-requests;";
  more_set_headers "Cross-Origin-Opener-Policy: same-origin";
  more_set_headers "Cross-Origin-Embedder-Policy: require-corp";
  more_set_headers "Cross-Origin-Resource-Policy: same-origin";

  location / {
    root /app/frontend;
    try_files $uri /index.html;
  }

  location /images/gravatar {
    alias /data/npmplus/gravatar/;
  }

  location /api {
    include proxy-headers.conf;
    proxy_set_header Accept-Encoding "";
    proxy_pass http://npmplus$request_uri;
  }
}
