server {
    server_name "";
    listen 0.0.0.0:81 ssl;
    listen [::]:81 ssl;
    ssl_reject_handshake on;
    return 444;
}

server {
    listen 0.0.0.0:81 ssl reuseport deferred so_keepalive=on default_server;
    listen [::]:81 ssl reuseport deferred so_keepalive=on default_server;

    server_name _;
    ssl_certificate ;
    ssl_certificate_key ;
    #ssl_stapling on;
    #ssl_stapling_verify on;
    #ssl_stapling_file ;
    #ssl_certificate_compression off;

    if ($scheme = "http") {
        return 301 https://$host$is_request_port$request_port$request_uri;
    }
    if ($http_x_forwarded_proto = "http") {
        return 301 https://$host$is_request_port$request_port$request_uri;
    }

    client_max_body_size 1m;
    more_set_headers "X-Frame-Options: DENY";
    more_set_headers "Referrer-Policy: no-referrer";
    more_set_headers "Content-Security-Policy: default-src 'self'; script-src 'self' 'sha256-vdSyDjhE3ZMSkQMKmAlr9J2BmPtY//4BwPgxvF99yZE=' 'sha256-DO5PcuswBpDi7xOFPuj86dwr9VuamByHpvk2ZDmlAAA='; style-src 'self' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha256-Xo8/tnRnpUxMw05nUf764oT49W2GEbQN9LaX8Wqxuwg='; img-src 'self' data:; base-uri 'self'; worker-src 'none'; object-src 'none';";

    location /api {
        include proxy-headers.conf;
        proxy_set_header Accept-Encoding "";
        proxy_pass http://unix:/run/npmplus.sock:$request_uri;
    }

    location /images/gravatar {
        alias /data/npmplus/gravatar/;
    }

    location / {
        root /app/frontend;
        try_files $uri /index.html;
    }
}
