#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/.common.sh"

# Ensure docker exists
if hash docker 2>/dev/null; then
	cd "${DIR}/.."
	rm -rf "$DIR/../test/results"
	docker compose up --build cypress
else
	echo -e "${RED}❯ docker command is not available${RESET}"
fi
