#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. $(dirname "$0")/log

COMPOSE_PROJECT_NAME="npmdev"
COMPOSE_FILE="docker/docker-compose.dev.yml"
export COMPOSE_FILE COMPOSE_PROJECT_NAME

# Ensure docker-compose exists
# Make sure docker exists
if hash docker-compose 2>/dev/null; then
	cd "${DIR}/.."
	log "Destroying Dev Stack ..." "info"
	docker-compose down --remove-orphans --volumes
else
	log "docker-compose command is not available" "danger"
fi
