#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. $(dirname "$0")/log

# Ensure docker-compose exists
if hash docker 2>/dev/null; then
	cd "${DIR}/.."
	log "Building Docs ..." "info"
	docker run --rm -e CI=true -v "$(pwd)/docs:/app/docs" -w /app/docs node:alpine sh -c "yarn install && yarn build && chown -R $(id -u):$(id -g) /app/docs"
	log "Building Docs Complete" "success"
else
	log "docker command is not available" "danger"
fi
