#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/.common.sh"

cd "${DIR}/.."
echo -e "${BLUE}❯ ${CYAN}Linting Frontend ...${RESET}"
docker run --rm -e CI=true -v "$(pwd)/frontend:/app/frontend" -w /app/frontend node:lts sh -c "yarn install && yarn eslint src;chown -R $(id -u):$(id -g) /app/frontend"
RES=$?
echo -e "${BLUE}❯ ${GREEN}Linting Frontend Complete${RESET}"
exit $RES

