#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/.common.sh"

# Ensure docker-compose exists
if hash docker 2>/dev/null; then
	cd "${DIR}/.."
	echo -e "${BLUE}❯ ${CYAN}Linting Frontend ...${RESET}"
	docker run --rm -e CI=true -v "$(pwd)/frontend:/app/frontend" -w /app/frontend node:20 sh -c "yarn install && yarn eslint src;chown -R $(id -u):$(id -g) /app/frontend"
	RES=$?
	echo -e "${BLUE}❯ ${GREEN}Linting Frontend Complete${RESET}"
	exit $RES
else
	echo -e "${RED}❯ docker command is not available${RESET}"
	exit 1
fi
