#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/.common.sh"

cd "${DIR}/.."

echo ""
inform "Tip: List tables with:      \\dt"
echo ""

docker compose exec npm usql /data/nginxproxymanager.db

