#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/.common.sh"

# Ensure docker-compose exists
# Make sure docker exists
if hash docker-compose 2>/dev/null; then
	cd "${DIR}/.."
	echo -e "${BLUE}❯ ${CYAN}Stopping Dev Stack ...${RESET}"
	docker-compose down --remove-orphans
else
	echo -e "${RED}❯ docker-compose command is not available${RESET}"
fi
