#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. $(dirname "$0")/log

COMPOSE_PROJECT_NAME="npmdev"
COMPOSE_FILE="docker/docker-compose.dev.yml"
export COMPOSE_FILE COMPOSE_PROJECT_NAME

# Ensure docker-compose exists
if hash docker-compose 2>/dev/null; then
	cd "${DIR}/.."
	log "Testing Dev Stack ..." "info"
	docker-compose exec -T npm bash -c "cd /app/backend && task test"
else
  log "docker-compose command is not available" "danger"
fi
