#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/.common.sh"

if [ "$1" == "" ]; then
	echo "Waits for a docker container to be healthy."
	echo "Usage: $0 docker-container 30"
	exit 1
fi

SERVICE=$1
LIMIT=${2:-90}

echo -e "${BLUE}❯ ${CYAN}Waiting for healthy: ${YELLOW}${SERVICE}${RESET}"

is_up() {
	docker exec "$SERVICE" /bin/healthcheck.sh
}

i=0
while ! is_up; do
	i=$((i + 1))
	if [ "$i" == "$LIMIT" ]; then
		echo -e "${BLUE}❯ ${RED}Timed out waiting for healthy${RESET}"
		docker logs --tail 50 "$SERVICE"
		exit 1
	fi
	sleep 1
done

echo ""
echo -e "${BLUE}❯ ${GREEN}Healthy!${RESET}"
