location ~* ^.*\.(css|js|jpe?g|gif|png|webp|woff|woff2|eot|ttf|svg|ico|css\.map|js\.map)$ {
  if_modified_since off;
  proxy_cache public-cache;
  proxy_cache_key $host$request_uri;
  proxy_ignore_headers Set-Cookie Cache-Control Expires X-Accel-Expires;
  proxy_cache_valid any 30m;
  proxy_cache_valid 404 1m;
  proxy_hide_header Last-Modified;
  proxy_hide_header Cache-Control;
  proxy_hide_header Vary;
  proxy_cache_bypass 0;
  proxy_no_cache 0;
  proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504 http_404;
  proxy_connect_timeout 5s;
  proxy_read_timeout 45s;
  expires @30m;
  access_log off;

  add_header X-Served-By $host;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Scheme $x_forwarded_scheme;
  proxy_set_header X-Forwarded-Proto $x_forwarded_proto;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_pass {{ forward_scheme }}://{{ upstream_group }}$request_uri;
}
