# ------------------------------------------------------------
# {{ name }}
# ------------------------------------------------------------

upstream upstream_host_{{ id }} {
{% if method == "least_conn" %}
  least_conn;
{% elsif method == "ip_hash" %}
  ip_hash;
{% endif %}
{% for server in servers %}
  server {{ server.host }}:{{ server.port }}{% if server.weight and method != "ip_hash" %} weight={{ server.weight }}{% endif %};
{% endfor %}
}
