name: Shellcheck
on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:
jobs:
  shellcheck:
    name: Check Shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # master
        with:
          check_together: 'yes'
#        env:
#          SHELLCHECK_OPTS: --shell sh -e SC1091 -e SC2153 -e SC2154
